# Generated by Django 4.0.3 on 2022-07-28 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
